### ISSUE TITLE
Disable 3D-Secure

### ISSUE THREAD

**Issue by kevindesousa** [cviebrock/laravel-mangopay#6]
Hello,

The Api FAQ said to disable 3D-Secure, we must to unset the SecureMode.
Bu this doesn't work. Do you have a solution ?

**Comment by cviebrock** [comment]
To be honest, I don't work on any projects that use Mangopay anymore, so I don't think I can help.

That said, this package is pretty much a wrapper for the official SDK, so where in the FAQ does it say to disable it?  I think the best you can do is using `"SecureMode": "DEFAULT"` in your requests.

**Comment by cviebrock** [comment]
Closing due to no response.  Feel free to re-open or comment if you are still having issues.
