### ISSUE TITLE
Laravel 6

### ISSUE THREAD

**Issue by AntoineLX** [cviebrock/laravel-mangopay#7]
Can you please provide support for laravel 6 ?

**Comment by cviebrock** [comment]
Hey @AntoineLX ... I see you closed the ticket, but I just released version 6.0.0 of the package, which should work with Laravel 6.0.

If you have a second to test it, that would be great, since I don't have anyway to do so with a live Mangopay account anymore.

**Comment by AntoineLX** [comment]
Yep sorry for that. 

I saw on an other issue that you do not work on this package anymore. So, i created a simple ServiceProvider that embed the mango php sdk.

I'll give a try to the update and tell you if it's ok.

**Comment by AntoineLX** [comment]
Seems to be ok :)
